//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theme_18_HomeWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int id { get; set; }
        public string FirstName { get; set; }
        public string MidleName { get; set; }
        public string LastName { get; set; }
        public int ClientType { get; set; }
        public string FullName { get; set; }
        public bool GoodHistory { get; set; }
        public string Documents { get; set; }
    }
}
