//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theme_18_HomeWork
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MSSQLLocalDemoEntities : DbContext
    {
        public MSSQLLocalDemoEntities()
            : base("name=MSSQLLocalDemoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccauntType> AccauntType { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<ClientType> ClientType { get; set; }
        public virtual DbSet<Organisations> Organisations { get; set; }
        public virtual DbSet<ratesType> ratesType { get; set; }
        public virtual DbSet<Accaunts> Accaunts { get; set; }
    
        public virtual int NextAccauntId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NextAccauntId");
        }
    
        public virtual int NextClientId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NextClientId");
        }
    }
}
