//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Theme_18_HomeWork
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Organisation
    {
        public int id { get; set; }
        public int ClientTypeId { get; set; }
        public string OrganisationName { get; set; }
        public bool GoodHistory { get; set; }
        public string BankDetails { get; set; }
        public string Adress { get; set; }
        public int ClientTypeid { get; set; }
    }
}
